// ActivityAction enum values
// These mirror the Prisma schema enum. Defined here to avoid depending
// on Prisma client generation (which can fail due to file locks on Windows).
const ActivityAction = {
  TASK_CREATED: "TASK_CREATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DELETED: "TASK_DELETED",
  CLIENT_CREATED: "CLIENT_CREATED",
  CLIENT_UPDATED: "CLIENT_UPDATED",
  CLIENT_DELETED: "CLIENT_DELETED",
  CREDENTIAL_CREATED: "CREDENTIAL_CREATED",
  CREDENTIAL_UPDATED: "CREDENTIAL_UPDATED",
  CREDENTIAL_DELETED: "CREDENTIAL_DELETED",
  USER_CREATED: "USER_CREATED",
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_UPDATED: "INVOICE_UPDATED",
  INVOICE_DELETED: "INVOICE_DELETED",
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  COMPLIANCE_CREATED: "COMPLIANCE_CREATED",
  COMPLIANCE_UPDATED: "COMPLIANCE_UPDATED",
  COMPLIANCE_COMPLETED: "COMPLIANCE_COMPLETED",
  DOCUMENT_CREATED: "DOCUMENT_CREATED",
  DOCUMENT_UPDATED: "DOCUMENT_UPDATED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_UPDATED: "TICKET_UPDATED",
  TICKET_RESOLVED: "TICKET_RESOLVED",
  USER_UPDATED: "USER_UPDATED",
  PASSWORD_RESET: "PASSWORD_RESET",
  USER_DISABLED: "USER_DISABLED",
  USER_ENABLED: "USER_ENABLED",
  USER_DELETED: "USER_DELETED"
};

module.exports = ActivityAction;
